# Generated by Django 3.1.1 on 2021-06-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smc', '0002_auto_20210627_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceLetter',
            fields=[
                ('letter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smc.letter')),
                ('grievance_letter', models.FileField(upload_to='')),
            ],
            bases=('smc.letter',),
        ),
    ]
